added Menu.cs with menu displaying and navigating logic
infoshareacademy/jcszr4-C_bool pull request #4
Opened 2021-10-08 19:16 UTC by andrzejpalica

Tu mam szkielet menu, natomiast musze jeszcze zaimplementowac to menu, tylko do tego potrzebuje juz miec nasze metody z repozytoriow,

2021-10-09 10:37 UTC, maciej-walas requested changes
Kurde, to jest MENU a nie jakieś tam menu, działa to za----ście. Z tymi komentarzami to naprawdę tylko tycie uwagi, bo za całość szacun!

Załączam w pliku jak coś klasę z moimi zmianami, możesz spojrzeć jak chcesz, głównie chodziło o zmianę List na Dictionary, machnąłem też parę wizualnych ficzerów, żeby było myślę czytelniej się poruszać po menu. Więcej pomysłów nie mam :-)
[Menu.zip](https://github.com/infoshareacademy/jcszr4-C_bool/files/7315400/Menu.zip)

2021-10-09 10:37 UTC, maciej-walas commented on C_bool.ConsoleApp/Menu.cs
> +        private static readonly List<string> _dataSourceList = new()
zmieniłbym na dictionary może, żeby switcha później robić po kluczu

2021-10-09 10:37 UTC, maciej-walas commented on C_bool.ConsoleApp/Menu.cs
> +            switch (SelectPositionFromMenu(_menuList))
No, właśnie tutaj :-)

2021-10-09 10:37 UTC, maciej-walas commented on C_bool.ConsoleApp/Menu.cs
> +                    menu[index] = menu[index].Replace('>', ' ');
_indicator jest zadeklarowany w zmiennej, można użyć zamiast wpisywać

2021-10-09 10:37 UTC, maciej-walas commented on C_bool.ConsoleApp/Menu.cs
> +                    Console.ForegroundColor = ConsoleColor.White;
Można użyć Console.ResetColor()

2021-10-09 11:05 UTC, andrzejpalica commented on C_bool.ConsoleApp/Menu.cs
> +        private static readonly List<string> _dataSourceList = new()
no tylko pytanie, co w tym slowniku uzyc jako klucz? bo jesli 1, 2, 3... to nie ma sensu bo lista przeciez ma indeksy wiec moge wtedy indeksow uzyc w switchu. Jesli masz jakis inny pomysl na klucz to dawaj bo mi wlasnie nic nie przyszlo do glowy wiec uzylem listy.

2021-10-09 11:11 UTC, andrzejpalica commented on C_bool.ConsoleApp/Menu.cs
> +            switch (SelectPositionFromMenu(_menuList))
moge zrobic zeby metoda SelectPositionFromMenu zwracala indeks, na ktorym znajduje sie wskaznik. no i potem w case'ach sprawdzac ten indeks. Pytanie tylko czy to bedzie bardziej czytelne dla kogos kto czyta ten kod. Bo bedzie mial tylko jakies wartosci 0, 1, 2 itp i skad bedzie wiedzial jaka metoda pod tym zaimplementowac. Ja sam nie wiem, ktore podejscie jest lepsze bo z jednej strony jak mam tekst to od razu wiem co pod nim implementowac a z drugiej strony z indekasmi by to na pewno wygladalo schludniej i tak bardziej profesjonalnie. Takze w sumie jesli uwazacie ze lepiej jest po indeksach to no problemo, bede to zaraz zmienial.

2021-10-09 11:15 UTC, andrzejpalica commented on C_bool.ConsoleApp/Menu.cs
> +                    Console.ForegroundColor = ConsoleColor.White;
wlasnie pamietalem ze w zadaniu domowym jakos inaczej wracalem do podstawowego koloru a nie moglem sobie przypomniec jak. Dzieki, zaraz to podmienie.

2021-10-09 11:15 UTC, andrzejpalica commented on C_bool.ConsoleApp/Menu.cs
> +                    menu[index] = menu[index].Replace('>', ' ');
true, zaraz mieniam wszedzie gdzie jest '>' na _indicator. w sumie probowalem juz to zrobic tez w tym switchu powyzej bo stwiedzilem ze przeciez ten wskaznik mozna sobie zmnienic na jakis inny, ale jak robilem _indicator + jakis tam tekst w case'ie to mi wywalalo blad ze tak nie mozna. Wiec to moze kolejny argument zeby jednak zmienic na indeksy tam. :)

2021-10-10 16:24 UTC, ValdesQ commented
Dla mnie super menu

2021-10-10 16:42 UTC, merged